// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwT6FthLIq15Y9oT18VrPg6PtwEUw3qOo',
    appId: '1:794568903689:web:0a56ac1dd77390b0e63cd8',
    messagingSenderId: '794568903689',
    projectId: 'binoy-dummy-project',
    authDomain: 'binoy-dummy-project.firebaseapp.com',
    storageBucket: 'binoy-dummy-project.appspot.com',
    measurementId: 'G-KK9F2D0CWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCApq07pNLeOg4aYSkRZ1YOqb2zHR7wD3o',
    appId: '1:794568903689:android:7d58ee78c5ee0964e63cd8',
    messagingSenderId: '794568903689',
    projectId: 'binoy-dummy-project',
    storageBucket: 'binoy-dummy-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_hlmc3dAfpngR5W87l7UNpqjB9yRnwVk',
    appId: '1:794568903689:ios:d47d85d8b5865946e63cd8',
    messagingSenderId: '794568903689',
    projectId: 'binoy-dummy-project',
    storageBucket: 'binoy-dummy-project.appspot.com',
    iosBundleId: 'com.binoydipu.dummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_hlmc3dAfpngR5W87l7UNpqjB9yRnwVk',
    appId: '1:794568903689:ios:d47d85d8b5865946e63cd8',
    messagingSenderId: '794568903689',
    projectId: 'binoy-dummy-project',
    storageBucket: 'binoy-dummy-project.appspot.com',
    iosBundleId: 'com.binoydipu.dummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwT6FthLIq15Y9oT18VrPg6PtwEUw3qOo',
    appId: '1:794568903689:web:93cc28c3cf2291f0e63cd8',
    messagingSenderId: '794568903689',
    projectId: 'binoy-dummy-project',
    authDomain: 'binoy-dummy-project.firebaseapp.com',
    storageBucket: 'binoy-dummy-project.appspot.com',
    measurementId: 'G-DVYBVGT908',
  );
}